package fun.oook.lottery.commons.db.entity;

import java.io.Serializable;

public class ViewGameHitNum implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_hit_num.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_hit_num.gameid
     *
     * @mbg.generated
     */
    private Integer gameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_hit_num.num
     *
     * @mbg.generated
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_game_hit_num
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_hit_num.id
     *
     * @return the value of view_game_hit_num.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_hit_num.id
     *
     * @param id the value for view_game_hit_num.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_hit_num.gameid
     *
     * @return the value of view_game_hit_num.gameid
     *
     * @mbg.generated
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_hit_num.gameid
     *
     * @param gameid the value for view_game_hit_num.gameid
     *
     * @mbg.generated
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_hit_num.num
     *
     * @return the value of view_game_hit_num.num
     *
     * @mbg.generated
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_hit_num.num
     *
     * @param num the value for view_game_hit_num.num
     *
     * @mbg.generated
     */
    public void setNum(Long num) {
        this.num = num;
    }
}