package fun.oook.lottery.commons.db.mapper;

import fun.oook.lottery.commons.db.entity.ViewGameCurinfo;
import fun.oook.lottery.commons.db.entity.ViewGameCurinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface ViewGameCurinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    long countByExample(ViewGameCurinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    int deleteByExample(ViewGameCurinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    @Insert({
        "insert into view_game_curinfo (title, starttime, ",
        "endtime, total, ",
        "hit, type)",
        "values (#{title,jdbcType=VARCHAR}, #{starttime,jdbcType=TIMESTAMP}, ",
        "#{endtime,jdbcType=TIMESTAMP}, #{total,jdbcType=DECIMAL}, ",
        "#{hit,jdbcType=BIGINT}, #{type,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(ViewGameCurinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    int insertSelective(ViewGameCurinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    List<ViewGameCurinfo> selectByExample(ViewGameCurinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewGameCurinfo record, @Param("example") ViewGameCurinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_curinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewGameCurinfo record, @Param("example") ViewGameCurinfoExample example);
}