package fun.oook.lottery.commons.db.mapper;

import fun.oook.lottery.commons.db.entity.ViewGameProductNum;
import fun.oook.lottery.commons.db.entity.ViewGameProductNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface ViewGameProductNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_product_num
     *
     * @mbg.generated
     */
    long countByExample(ViewGameProductNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_product_num
     *
     * @mbg.generated
     */
    int deleteByExample(ViewGameProductNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_product_num
     *
     * @mbg.generated
     */
    @Insert({
        "insert into view_game_product_num (gameid, num)",
        "values (#{gameid,jdbcType=INTEGER}, #{num,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(ViewGameProductNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_product_num
     *
     * @mbg.generated
     */
    int insertSelective(ViewGameProductNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_product_num
     *
     * @mbg.generated
     */
    List<ViewGameProductNum> selectByExample(ViewGameProductNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_product_num
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewGameProductNum record, @Param("example") ViewGameProductNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_product_num
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewGameProductNum record, @Param("example") ViewGameProductNumExample example);
}