package fun.oook.lottery.commons.db.mapper;

import fun.oook.lottery.commons.db.entity.ViewCardUserHit;
import fun.oook.lottery.commons.db.entity.ViewCardUserHitExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface ViewCardUserHitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_card_user_hit
     *
     * @mbg.generated
     */
    long countByExample(ViewCardUserHitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_card_user_hit
     *
     * @mbg.generated
     */
    int deleteByExample(ViewCardUserHitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_card_user_hit
     *
     * @mbg.generated
     */
    @Insert({
        "insert into view_card_user_hit (title, uname, ",
        "realname, idcard, ",
        "phone, name, price, ",
        "hittime, userid, ",
        "gameid, productid, ",
        "level, type, starttime, ",
        "endtime)",
        "values (#{title,jdbcType=VARCHAR}, #{uname,jdbcType=VARCHAR}, ",
        "#{realname,jdbcType=VARCHAR}, #{idcard,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL}, ",
        "#{hittime,jdbcType=TIMESTAMP}, #{userid,jdbcType=INTEGER}, ",
        "#{gameid,jdbcType=INTEGER}, #{productid,jdbcType=INTEGER}, ",
        "#{level,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, #{starttime,jdbcType=TIMESTAMP}, ",
        "#{endtime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(ViewCardUserHit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_card_user_hit
     *
     * @mbg.generated
     */
    int insertSelective(ViewCardUserHit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_card_user_hit
     *
     * @mbg.generated
     */
    List<ViewCardUserHit> selectByExample(ViewCardUserHitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_card_user_hit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewCardUserHit record, @Param("example") ViewCardUserHitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_card_user_hit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewCardUserHit record, @Param("example") ViewCardUserHitExample example);
}