package fun.oook.lottery.commons.db.mapper;

import fun.oook.lottery.commons.db.entity.ViewUserHitNum;
import fun.oook.lottery.commons.db.entity.ViewUserHitNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface ViewUserHitNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_hit_num
     *
     * @mbg.generated
     */
    long countByExample(ViewUserHitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_hit_num
     *
     * @mbg.generated
     */
    int deleteByExample(ViewUserHitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_hit_num
     *
     * @mbg.generated
     */
    @Insert({
        "insert into view_user_hit_num (userid, num)",
        "values (#{userid,jdbcType=INTEGER}, #{num,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(ViewUserHitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_hit_num
     *
     * @mbg.generated
     */
    int insertSelective(ViewUserHitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_hit_num
     *
     * @mbg.generated
     */
    List<ViewUserHitNum> selectByExample(ViewUserHitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_hit_num
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewUserHitNum record, @Param("example") ViewUserHitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_hit_num
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewUserHitNum record, @Param("example") ViewUserHitNumExample example);
}