package fun.oook.lottery.commons.db.mapper;

import fun.oook.lottery.commons.db.entity.ViewGameHitNum;
import fun.oook.lottery.commons.db.entity.ViewGameHitNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface ViewGameHitNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_hit_num
     *
     * @mbg.generated
     */
    long countByExample(ViewGameHitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_hit_num
     *
     * @mbg.generated
     */
    int deleteByExample(ViewGameHitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_hit_num
     *
     * @mbg.generated
     */
    @Insert({
        "insert into view_game_hit_num (gameid, num)",
        "values (#{gameid,jdbcType=INTEGER}, #{num,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(ViewGameHitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_hit_num
     *
     * @mbg.generated
     */
    int insertSelective(ViewGameHitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_hit_num
     *
     * @mbg.generated
     */
    List<ViewGameHitNum> selectByExample(ViewGameHitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_hit_num
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewGameHitNum record, @Param("example") ViewGameHitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_game_hit_num
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewGameHitNum record, @Param("example") ViewGameHitNumExample example);
}